### PR TITLE
SearchLPSHiGHS.cmake: use absolute library paths in pkgconfig case

### PR DESCRIPTION
**Pull request by jgillis**

### CODE REVIEW

**Comment by chrhansk** [comment]
One question regarding https://github.com/chrhansk/sleqp/pull/2/commits/a22cb46b9cb29f8eb93a445ca3d9d9e2322160e8:

Apparently the HiGHS libraries are not found when they are in a non-standard location, correct? 

Could you show me the relevant portion of the generated `CMakeCache.txt` (lines mentioning highs)?

Because I would have thought that the pkg-config interface should have set `HIGHS_LIBRARY_DIRS`, which should have set `SLEQP_LPS_LIBRARY_DIRS` which should have been included in the `SLEQP_LIBRARY_DIRS` which should be included in the link directories of the main library.

**Comment by jgillis** [comment]
Okay didn't about this route. The problem was occuring for mingw crossbuilds.

**Comment by chrhansk** [comment]
Well, apparently there is a bug in that route, since it is failing... Based on a full CMakeCache file I could try my hand at debugging it.

**Comment by chrhansk** [comment]
I will probably merge them in parts, sorting out some issues along the way

- [ ] a22cb46 SearchLPSHiGHS.cmake: use absolute library paths in pkgconfig case
- [x] 8adc0b9 Fix symbol export on Windows
- [x] 7855d55 Harden against gnu11
- [x] 68cebb3 Make MPI requirement for MUMPS conditional
- [x] fa2af1b More hardening against gnu11
- [x] 49d130a Adding sleqp_settings_set_enum_value_by_string
- [x] 488bf51 Compatibility with coinmumps and absense of MPI
- [x] 12e9fc9 Make sure libsleqp.dll gets installed

Edit: Renamed the function to `sleqp_settings_set_enum_value_from_string`

**Comment by chrhansk** [comment]
The last issue is that of the library paths in pkg-config. Again, I would like to better understand the underlying problem. Could you provide me with the relevant `CMakeCache.txt`?

**Comment by jgillis** [comment]
> The last issue is that of the library paths in pkg-config. Again, I would like to better understand the underlying problem. Could you provide me with the relevant `CMakeCache.txt`?

I fail to reproduce it at the moment, may have been a fluke..

**Comment by jgillis** [comment]
The CI system also does not pick up the issue anymore. Let's forget about a22cb46b9cb29f8eb93a445ca3d9d9e2322160e8

**Pull request closed without merging**
